version: '3.8'

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./src:/app/src
      - /app/node_modules
    environment:
      - NODE_ENV=production
    restart: unless-stopped